version: '3'
services:
  gstant:
    image: gstant/general-server-assistant:aio
    container_name: general-server-assistant
    restart: always
    ports:
      - 9999:9999
      - 3000:3000
    volumes:
      - /home/admin/config:/home/gstant/general-server-assistant/config/
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:4.0
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: gstant
      
   
    volumes:
      - /home/admin/data/db:/data/db
      - /etc/localtime:/etc/localtime
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
