version: '3'
services:
  gstant:
    image: gstant/general-server-assistant:latest
    container_name: general-server-assistant
    restart: always
    ports:
      - 9999:9999
    volumes:
      - ./gstant/config:/home/gstant/general-server-assistant/config/
      - ./gstant/plugins:/home/gstant/general-server-assistant/app/plugins
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:4.0.26
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./data/db:/data/db
      - /etc/localtime:/etc/localtime
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
